export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_FILE = 'UPDATE_FILE'
export const UPDATE_CURRENT_IDX = 'UPDATE_CURRENT_IDX'
export const UPDATE_FILE_LIST = 'UPDATE_FILE_LIST'
export const UPDATE_CODE = 'UPDATE_CODE'
export const UPDATE_ACTIVE_CONTRIBUTOR= 'UPDATE_ACTIVE_CONTRIBUTOR'

export const SHOW_DIMMER = 'SHOW_DIMMER'
export const HIDE_DIMMER = 'HIDE_DIMMER'
export const SHOW_MESSAGE_BOX = 'SHOW_MESSAGE_BOX'
export const HIDE_MESSAGE_BOX = 'HIDE_MESSAGE_BOX'
export const SHOW_REGIST_BOX = 'SHOW_REGIST_BOX'
export const HIDE_REGIST_BOX = 'HIDE_REGIST_BOX'
export const SHOW_PROFILE_BOX = 'SHOW_PROFILE_BOX'
export const HIDE_PROFILE_BOX = 'HIDE_PROFILE_BOX'
export const SHOW_LOADING = "SHOW_LOADING"
export const HIDE_LOADING = "HIDE_LOADING"

export const UPDATE_HOSTS = 'UPDATE_HOSTS'
export const UPDATE_CONTRIBUTORS = 'UPDATE_CONTRIBUTORS'
export const ADD_CONTRIBUTOR = 'ADD_CONTRIBUTOR'

export const SWITCH_CONSOLE_MENU = 'SWITCH_CONSOLE_MENU'

export const INITIALIZE_SOCKET = 'INITIALIZE_SOCKET'

export const SEND_MESSAGE = 'SEND_MESSAGE'
