exports.JOIN_IDE = "JOIN:IDE"
exports.UPDATE_CODE = "UPDATE:CODE"
exports.CHAT_MESSAGE = "CHAT:MESSAGE"

exports.CONTAINER_INIT = "CONTAINER:INIT"
exports.CONTAINER_CP = "CONTAINER:CP"
exports.CONTAINER_COMMAND = "CONTAINER:COMMAND"

exports.DISCONNECT = "disconnect"